In [20]:
import pandas as pd
import numpy as np

In [21]:
# Loading the dataset using pandas

df = pd.read_csv("D:/ABHAY/Projects/Bank_Customer_Churn_Project/data/raw/Churn_Modelling.csv")

In [22]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [23]:
# Check datatypes

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  str
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  str
 5   Gender           10000 non-null  str
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), str(3)
memory usage: 1.1 MB

In [24]:
# Check shape

df.shape

(10000, 14)

In [25]:
# Summary statistics using .describe()

df.describe(include='all')

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000,10000.000000,10000,10000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
unique,NaN,NaN,2932,NaN,3,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,Smith,NaN,France,Male,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,32,NaN,5014,5457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,5000.50000,1.569094e+07,NaN,650.528800,NaN,NaN,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,NaN,96.653299,NaN,NaN,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,NaN,350.000000,NaN,NaN,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,NaN,584.000000,NaN,NaN,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,NaN,652.000000,NaN,NaN,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,NaN,718.000000,NaN,NaN,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,NaN,850.000000,NaN,NaN,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [26]:
# Checking if missing data or null values are present in the dataset

df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [27]:
# Checking if duplicates values are present in the dataset

df.duplicated().sum()

np.int64(0)

In [28]:
# Removing Unnecessary Columns but in this case we remove only one columns but in case you have to
# remove many columns this is the method in drop_cols you can add multiple columns names....

drop_cols = [
    "RowNumber"
]

df = df.drop(columns=drop_cols)
df.head(5)

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [29]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CustomerId       10000 non-null  int64
 1   Surname          10000 non-null  str
 2   CreditScore      10000 non-null  int64
 3   Geography        10000 non-null  str
 4   Gender           10000 non-null  str
 5   Age              10000 non-null  int64
 6   Tenure           10000 non-null  int64
 7   Balance          10000 non-null  float64
 8   NumOfProducts    10000 non-null  int64
 9   HasCrCard        10000 non-null  int64
 10  IsActiveMember   10000 non-null  int64
 11  EstimatedSalary  10000 non-null  float64
 12  Exited           10000 non-null  int64
dtypes: float64(2), int64(8), str(3)
memory usage: 1015.8 KB

In [30]:
df.shape

(10000, 13)

In [31]:
# create a new column churn_status

df["Churn_Status"] = df["Exited"].map({ 0 : "Retained", 1:"Churned"})

In [32]:
df.head()

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Churn_Status
0,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1,Churned
1,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,Retained
2,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,Churned
3,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0,Retained
4,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,Retained

In [33]:
# create a new column age_group

df["Age_Group"] = pd.cut(df["Age"], 
                         bins = [18,30,40,50,60,100],
                         labels = [
                             "18-30",
                             "31-40",
                             "41-50",
                             "51-60",
                             "60+"
                         ], include_lowest=True
                        )

In [34]:
df.head()

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Churn_Status,Age_Group
0,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1,Churned,41-50
1,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,Retained,41-50
2,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,Churned,41-50
3,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0,Retained,31-40
4,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,Retained,41-50

In [35]:
df[df['Age'] == 18]

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Churn_Status,Age_Group
746,15787619,Hsieh,844,France,Male,18,2,160980.03,1,0,0,145936.28,0,Retained,18-30
1619,15770309,McDonald,656,France,Male,18,10,151762.74,1,0,1,127014.32,0,Retained,18-30
1678,15569178,Kharlamov,570,France,Female,18,4,82767.42,1,1,0,71811.90,0,Retained,18-30
2021,15795519,Vasiliev,716,Germany,Female,18,3,128743.80,1,0,0,197322.13,0,Retained,18-30
2136,15621893,Bellucci,727,France,Male,18,4,133550.67,1,1,1,46941.41,0,Retained,18-30
2141,15758372,Wallace,674,France,Male,18,7,0.00,2,1,1,55753.12,1,Churned,18-30
3330,15657439,Chao,738,France,Male,18,4,0.00,2,1,1,47799.15,0,Retained,18-30
3512,15657779,Boylan,806,Spain,Male,18,3,0.00,2,1,1,86994.54,0,Retained,18-30
3517,15757821,Burgess,771,Spain,Male,18,1,0.00,2,0,0,41542.95,0,Retained,18-30
3686,15665327,Cattaneo,706,France,Male,18,2,176139.50,2,1,0,129654.22,0,Retained,18-30
4556,15796231,Nwankwo,681,France,Female,18,1,98894.39,1,1,1,9596.40,0,Retained,18-30
4716,15805764,Hallahan,646,France,Male,18,10,0.00,2,0,1,52795.15,0,Retained,18-30
7334,15759133,Vaguine,616,France,Male,18,6,0.00,2,1,1,27308.58,0,Retained,18-30
7722,15570086,Lynch,684,Germany,Male,18,9,90544.00,1,0,1,4777.23,0,Retained,18-30
8522,15619892,Page,644,Spain,Male,18,8,0.00,2,1,0,59172.42,0,Retained,18-30
9029,15722701,Bruno,594,Germany,Male,18,1,132694.73,1,1,0,167689.56,0,Retained,18-30
9501,15634146,Hou,835,Germany,Male,18,2,142872.36,1,1,1,117632.63,0,Retained,18-30
9520,15673180,Onyekaozulu,727,Germany,Female,18,2,93816.70,2,1,0,126172.11,0,Retained,18-30
9526,15665521,Chiazagomekpele,642,Germany,Male,18,5,111183.53,2,0,1,10063.75,0,Retained,18-30
9572,15641688,Collier,644,Spain,Male,18,7,0.00,1,0,1,59645.24,1,Churned,18-30
9782,15728829,Weigel,509,France,Male,18,7,102983.91,1,1,0,171770.58,0,Retained,18-30
9932,15813451,Fleetwood-Smith,677,Spain,Male,18,8,134796.87,2,1,1,114858.90,0,Retained,18-30

In [36]:
# Renaming columns according to snake casing for better readability and documentation
df.columns = df.columns.str.lower()
df = df.rename(columns={'customerid':'customer_id',
                        'creditscore':'credit_score',
                        'numofproducts':'num_of_products',
                        'hascrcard':'has_cr_card',
                        'isactivemember':'is_active_member',
                        'estimatedsalary':'estimated_salary',
                       })

In [37]:
# Save Cleaned Data to csv

df.to_csv("D:/ABHAY/Projects/Bank_Customer_Churn_Project/data/cleaned/churn_cleaned.csv")

## Connecting Python script to PostgreSQL

In [38]:
from sqlalchemy import create_engine

# Step 1: Connect to PostgreSQL
# Replace placeholders with your actual details
username = "postgres"      # default user
password = "admin123" # the password you set during installation
host = "localhost"         # if running locally
port = "5432"              # default PostgreSQL port
database = "bank_churn_analysis"    # the database you created in pgAdmin

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

# Step 2: Load DataFrame into PostgreSQL
table_name = "bank_churn"   # choose any table name
df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'bank_churn' in database 'bank_churn_analysis'.

In [39]:
df.head(5)

,customer_id,surname,credit_score,geography,gender,age,tenure,balance,num_of_products,has_cr_card,is_active_member,estimated_salary,exited,churn_status,age_group
0,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1,Churned,41-50
1,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,Retained,41-50
2,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,Churned,41-50
3,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0,Retained,31-40
4,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,Retained,41-50